<template>
    <p class="description alert alert-light">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis diam at quam molestie egestas. Nullam varius malesuada ante, vel ultrices libero vestibulum et. Morbi eleifend eros et vulputate sagittis. Nullam laoreet, odio ut imperdiet facilisis, libero nisi luctus ipsum, in blandit nibh tortor vel eros. Maecenas feugiat tristique arcu, nec gravida velit feugiat dapibus. Curabitur iaculis massa at arcu ultricies, vel posuere ipsum fermentum. Phasellus facilisis magna ipsum, eget volutpat eros consequat vel. Pellentesque sed iaculis sapien, ac placerat mauris. Etiam et libero ullamcorper, rhoncus nisl et, pretium nisl. Quisque sit amet pharetra libero, nec maximus metus. Nulla hendrerit varius hendrerit. Phasellus bibendum finibus augue eu ornare. Mauris eget velit nec nisl maximus facilisis. Praesent vehicula tincidunt blandit. Ut ullamcorper nisl ut nibh tincidunt aliquam.

        Pellentesque lorem purus, volutpat a porttitor pulvinar, tempor at sapien. Nullam in tincidunt augue. Mauris tempor vulputate vestibulum. In egestas vehicula ornare. Donec venenatis ante ut diam ullamcorper, nec semper metus congue. Curabitur mollis pellentesque mi, ac imperdiet lectus. In mauris nunc, dignissim ut arcu sed, pretium rutrum lorem. Nunc malesuada tellus eu massa volutpat, in consectetur est porttitor. Ut mollis orci nisl, fringilla iaculis nunc euismod non. Nunc bibendum at orci quis varius. Fusce pulvinar augue non felis maximus, nec lobortis lacus dignissim. Praesent iaculis suscipit finibus. Etiam lorem augue, blandit vel condimentum sit amet, dictum at nisi.

        Quisque vitae dui nulla. Fusce nulla dui, porttitor et rhoncus ut, cursus eget ipsum. Aenean nisi purus, pretium et luctus at, eleifend nec ex. Donec semper mi efficitur purus sagittis, in pretium est accumsan. Aliquam scelerisque euismod elit, et elementum dui elementum sit amet. Nulla massa mi, rutrum a malesuada a, euismod et metus. Vestibulum ut laoreet odio. Nulla dui massa, fringilla eget leo nec, sagittis tempor libero. Sed est mauris, faucibus et lorem et, blandit iaculis leo. Sed et magna in libero consequat mattis porttitor eget mauris. Quisque pellentesque vel eros ac convallis. Vestibulum mollis lorem quis lectus ultricies dignissim. Curabitur turpis justo, porttitor ut lorem eget, viverra aliquet dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed condimentum accumsan ligula at bibendum.

        Suspendisse porttitor posuere nisl, vel egestas augue tristique rutrum. Vivamus a nisl interdum, suscipit nulla non, euismod urna. Cras ultricies arcu sed dolor accumsan dapibus. Duis eget nunc vulputate, molestie orci eu, suscipit arcu. Aliquam nec consectetur augue. Pellentesque et augue felis. Proin faucibus est non justo pretium, sit amet tincidunt ante aliquam. Donec ut elit ut dolor condimentum eleifend. Maecenas lacinia suscipit tortor, id vestibulum felis placerat at. Quisque fringilla enim in sem mollis, vitae laoreet ligula lacinia. Curabitur odio magna, pellentesque vel dui non, commodo commodo purus. Phasellus maximus eget quam elementum condimentum. 
    </p>
</template>

<style src="./stylesheets/AlgorithmDescription.css"></style>